config/routes.rb
Pointplace::Application.routes.draw do

  root :to => 'home#index'
  
  match 'signup' => 'users#new', :via => :get

  resource :session, :only => [:new, :create, :destroy]

  resource :account, :controller => 'users', :only => [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessor :password
  attr_protected :password_digest

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true, :email => true
  validates :password, :presence => true, :confirmation => true
  validates :password_confirmation, :presence => { :if => :password }
  validates :phone, :format => { :allow_nil => true, :with => /^[\(\)0-9\- \+\.]{10,20}\s*[extension\.]{0,9}\s*[0-9]{0,5}$/i }

  def self.authenticate(email, pass)
    user = where(:email => email).first
    user && BCrypt::Password.new(user.password_digest) == pass ? user : nil
  end
  
  def password=(pass)
    return if pass.blank?
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :except => :create 

  helper_method :current_user

  private

  def require_user
    return if current_user

    respond_to do |format|
      format.html { redirect_to login_path }
      format.all  { render :text => 'unauthorized', :status => :unauthorized }
    end
  end

  def current_user
    return @current_user if @current_user

    if session[:user_id]
      @current_user = User.find(session[:user_id])
    elsif (header = request.headers['Authorization'].to_s.sub('Basic ','')) != ''
      header = Base64.decode64(header).split(':')
      username = header.shift
      password = header.join(':')
      @current_user = User.authenticate(username, password)
    end
  end

  def create_user_session(user)
    session[:user_id] = user.id
  end

  def destroy_user_session
    session[:user_id] = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :json
  
	def create
    @user = User.authenticate(params[:email], params[:password])

    if @user
      create_user_session(@user)
      # respond_to do |format|
      #      format.json { render json: @user }
      # end
      respond_with @user, :location => '/', :notice => "Login succesful."
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render :json => {:error => "Invalid email or password."} }
      end
    end
  end

  def destroy
    destroy_user_session
    redirect_to '/', :notice => "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    # logger.debug "Params: #{params[:user]}"
    #  logger.debug "New user: #{@user.attributes.inspect}"
    # logger.debug "User should be valid: #{@user.valid?}"

    # if @user.save
    #   flash[:notice] = 'Account created.'
    # end
    # respond_with @user, :location => '/'

    if @user.save
        respond_to do |format|
           format.json { render json: @user }
        end
    else
      render :nothing => true
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pointplace</title>
 <meta content="width=device-width, minimum-scale=1, maximum-scale=1" name="viewport" charset="utf-8">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= requirejs_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div id="signup" class="panel" title="SignUp">
 <%= form_tag account_path, :class => 'form-horizontal' do %>
    <div class="control-group">
      <%= label_tag :name, nil, :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag :name, nil, :placeholder => 'Robert A. Jones' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :email, nil, :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag :email, nil, :placeholder => 'robert@example.com' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :password, nil, :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag :password_confirmation, 'Confirm', :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password_confirmation %>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag "Signup", :class => 'btn btn-primary' %>
      <div class='clear'></div>
    </div>

  <% end %>
  <div class='clear'></div>
</div>